language: node_js
node_js:
- '8.4'
notifications:
  slack:
    secure: IoBeCTzBygQUPVcGKuGJ7sEfGdqw1Z3snopz1kPjkSIzXKmE9mUj51AfbhUIEWx+SB88plXYiPFYP8zmSOKfVt8zFK6v/aUxt48i3IqsWRTNGy+/wYx+I4EizD4TbEfcaPNqzlHJwSTZoq6ejK7I7a8XAU8Ag6P13TGxOlFZmKQw7JE9LmnRrEA9ebqCyuzQELP1JQ55a3jHHeEdrGASsGkF6ArRLpWXHsD1Ssx8lICHj6N8Yoc9j7bmo8L/NM/LfHH1VE/4RS5WE4HS8PERRNGhTdPMdalAp2S/ltbFcvc3J496m5e5RfB02sb+AAFSRrnwRAldA6KF59I4ImgFjHFXg42pMjAwHZ6RYnFZo+8ZZKW8kvxNt7minvYDSsRYil5CLMqiQXjQcs+XCc6PcYpkrczEFUWiLNh7uI8M0czMfkvNbUkFvPWes3D4zIUL1qNuwXVxgnpLfQVbhjHlHOp7hJy4qhQHjz2v2yAqqKId5Tx5iTl/Y+5nzANQEQ2A3sjeL2Ts53qE4CiFg7V/Y7WCiWP9r643Go0J++2+VkNeewFL6mM8ULIX2EJ0NO/jSq9K9ZUc8u5RXVsSdoe/q2O/g8k0Ntf7B34Bn2uWeZJ4pWxaZJ2KKmUgrDUo2M4Ogk/n+yaG46DmIXz8cDbaI1vPsyRlCoTnF/+9YfxdcN8=
  on_success: never
  on_failure: always